language: node_js
node_js:
  - "stable"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
- ng lint
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
- ng build --prod
