language: node_js
node_js:
  - "stable"
dist: trusty
sudo: required

deploy:
  provider: heroku
  api_key:
    secure: ${{ secrets.HEROKU_API_KEY }}
  app: angular-rps-game

before_script:
  - npm install -g @angular/cli

script:
- ng lint
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
- ng build --prod
